name: flicker_cli
description: A sample command-line application.
version: 1.0.2
repository: https://github.com/EsinShadrach/flicker_cli

environment:
  # Switching to 43.6 cause the remove semi colons is ass.
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # Adding flutter for test and remove it later.
  flutter:
    sdk: flutter
  io: ^1.0.5
  args: ^2.6.0
  path: ^1.9.1
  infamous_squircle: ^0.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  flicker: flicker_cli
